### ISSUE TITLE
use spring.application.name default

### ISSUE THREAD

**Issue by jangalinski** [holunda-io/camunda-bpm-taskpool#565]
### Scenario

* camunda-bpm-taskpool version: 3.2.0
* Camunda BPM version: 7.16.0

### Current Behaviour

```yaml
polyflow:
  integration:
    sender:
      enabled: true
      data-entry:
        enabled: false
#        application-name: ${spring.application.name}  # default
```

if I remove the `application-name` property, app fails to start with 

```
Failed to bind properties under 'polyflow.integration.sender.data-entry' to io.holunda.polyflow.datapool.DataEntrySenderProperties:

    Reason: java.lang.NullPointerException: Parameter specified as non-null is null: method io.holunda.polyflow.datapool.DataEntrySenderProperties.<init>, parameter applicationName
```

### Wanted Behaviour

1. if I disable the feature, I do not want to do any further configuration
2. let application-name default to `spring.application.name` and only overwrite if needed

### Possible Workarounds

- set the superfluous property
